
import { Modal } from "@chakra-ui/react";
import Terreno from "../Terreno";

export const textos = {
  en: {
    navbar: {
      titulo: "Properties",
      contacto: "Contact",
    },
    formulario: {
      formulario: "Form", 
      enviar: "Send",
      nombre: "Name",
      apellido:"Last Name",
      Email: "Email",
      celular:"Mobile Phone",
      comentario:"Comment...",
      
    },
    inicio: {
      buscar: "Search by location...",
    },
    footer: {
      derechos: "Land Project. All rights reserved.",
      inmobiliario: "Cusco Real Estate",
      inicio: "Home",
      formulario: "Contact Form",
      redes: "Follow us on Social Media",
      cusco: "Your trusted real estate partner in Cusco",
      todo: "all",
      panel: "Administration Panel",
      telefono: "Phone",
      ubicacion: "Location",
      ciudad: "Cusco, Peru",
    },
    Terreno: {
        sinTerrenos:"No land was found",
        lista:"lands found",
        filtros:{
            limpiar:"Clean Filters",
            filtro:"Filters",
            tipo:"Land Type",
            todo:"All",
            urbano:"Urban",
            agricola:"Agricultural",
            localizacion:"Location",
            estado:"States",
            disponible:"Available",
            reservado:"Reserved",
            vendido:"Sold",
            rango:"Range",
            minimo:"Minimum",
            maximo:"Maximum",
            area:"Area",
            distrito:"District",   
        },
        modal:{
            urbano:"Urban land",
            agricola:"Agricultural land",
            localizacion:"Location",
            disponible:"AVAILABLE",
            reservado:"RESERVED",
            vendido:"SOLD",
        }
    },
    Modal:{
        precio:"Price",
        area:"Area",
        distrito:"District",
        publicado:"Published",
        descripcion:"Description",
        cerrar:"Close",
    }
  },
  es: {
    navbar: {
      terrenos: "Propiedades",
      contacto: "Contacto",
    },
    formulario: {
      formulario: "Formulario",
      enviar: "Enviar",
      nombre: "Nombre",
      apellido:"Apellido",
      Email: "Correo",
      celular:"Celular",
      comentario:"Comentario...",
    },
    inicio: {
      buscar: "Buscar por ubicación...",
    },
    footer: {
      derechos: "Proyecto Terrenos. Todos los derechos reservados",
      inmobiliario: "Inmobiliaria Cusco",
      inicio: "Inicio",
      formulario: "Formulario de Contacto",
      redes: "Síguenos en Redes Sociales",
      cusco: "Tu socio inmobiliario de confianza en Cusco",
      todo: "Todos",
      panel: "Panel de Administracion",
      telefono: "Teléfono",
      ubicacion: "Ubicación",
      ciudad: "Cusco, Perú", 
    },
    Terreno: {
        lista:"terrenos encontrados",
        sinTerrenos:"No se encontraron terrenos",
        filtros:{
            limpiar:"Limpiar Filtros",
            filtro:"Filtros",
            tipo:"Tipo de Terreno",
            todo:"Todos",
            urbano:"Urbano",
            agricola:"Agrícola",
            localizacion:"Localización",
            estado:"Estados",
            disponible:"Disponible",
            reservado:"Reservado",
            vendido:"Vendido",
            rango:"Rango",
            minimo:"Mínimo",
            maximo:"Máximo",
            area:"Área",
            distrito:"Distrito",   
        },
        modal:{
            urbano:"Terreno urbano",
            agricola:"Terreno agrícola",
            localizacion:"Localización",
            disponible:"DISPONIBLE",
            reservado:"RESERVADO",
            vendido:"VENDIDO",
        }
    },
    Modal:{
        precio:"Precio",
        area:"Área",
        distrito:"Distrito",
        publicado:"Publicado",
        descripcion:"Descripcion",
        cerrar:"Cerrar",
    }
    
  },
  qu: {
    navbar: {
      titulo: "Wasipi",
      contacto: "Rimaykuy",
    },
    formulario: {
      formulario: "Formulario",
      enviar: "Apachiy",
      nombre: "Suti",
      apellido:"Taytamama suti",
      Email: "Correo electrónico",
      celular:"Movil yupay",
      comentario:"Rimasqa..",
    },
    inicio: {
      buscar: "Maskay llaqtapi...",
    },
    footer: {
      derechos: "Proyecto de Tierra. Tukuy hayñikuna waqaychasqa.",
      inmobiliario: "Cusco Inmuebles",
      inicio: "Wasi",
      formulario: "Contacto Formulario",
      redes: "Qatiwayku Redes Sociales nisqapi",
      cusco: "Cusco llaqtapi inmuebles nisqapi hapipakuq masiyki",
      todo: "Tukuy",
      panel: "Panel de Administración",
      telefono: "Telefono",
      ubicacion: "Maypi tarikusqan",
      ciudad: "Cusku, Piruw",
    },
    Terreno: {
        sinTerrenos:"Mana allpata tarishkachu",
        lista:"allpa tarisqa",
        filtros:{
            limpiar:"P'uya Filtrokuna",
            filtro:"Filtrokuna",
            tipo:"Allpa Tipo",
            todo:"Tukuy",
            urbano:"Urbano",
            agricola:"Agricola",
            localizacion:"Localizacion",
            estado:"Stadas",
            disponible:"Kaq",
            reservado:"Waqaychasqa",
            vendido:"Rantisqa",
            rango:"Rango",
            minimo:"Aswan pisi",
            maximo:"Máximo",
            area:"Área",
            distrito:"Distritu",   
        },
        modal:{
            urbano:"Terreno Urbano",
            agricola:"Terreno Agrícola",
            localizacion:"Localización",
            disponible:"DISPONIBLE",
            reservado:"RESERVADO",
            vendido:"RANTIQA",
        }
    },
    Modal:{
        precio:"Precio",
        area:"Área",
        distrito:"Distritu",
        publicado:"Qillqasqa",
        descripcion:"Descripcion",
        cerrar:"Wisq'ay",
    }
  },
};
